version: '3.1'

services:
  api:
    image: python-template:0.0.1
    ports:
      - 80:8090
    environment:
      - COCKROACH_HOST=localhost
      - COCKROACH_PORT=26257
      - COCKROACH_USER=root
      - COCKROACH_DATABASE=test
      - COCKROACH_PASSWORD=
      - COCKROACH_SECURE=false
      - AWS_REGION=eu-west-1
      - DATA_PATH="data/"
  database:
    image: cockroachdb/cockroach:v20.2.19
    command: start-single-node --insecure
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 26257:26257
      - 8080:8080
