apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-template.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "python-template.name" . }}
    helm.sh/chart: {{ include "python-template.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data: {{ include "python-template.env.config" . | nindent 2 }}