apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "document-tokenizer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "document-tokenizer.name" . }}
    helm.sh/chart: {{ include "document-tokenizer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data: {{ include "document-tokenizer.env.config" . | nindent 2 }}