{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "document-tokenizer.fullname" . }}
  labels:
    {{- include "document-tokenizer.common.labels" . | nindent 4 }}
    helm.sh/chart: {{ template "document-tokenizer.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "document-tokenizer.fullname" . }}
  minReplicas: {{ default .Values.replicaCount .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics: {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
{{- end }}
