apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "python-template.fullname" . }}
  labels:
    {{- include "python-template.full.labels" . | nindent 4 }}
data: {{ include "python-template.env.secret" . | nindent 2 }}