{{- if .Values.secrets.dockerCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "document-tokenizer.fullname" . }}-docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson .Values.secrets.dockerCredentials | b64enc | quote }}
{{- end }}
