apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "document-tokenizer.fullname" . }}
  labels:
    {{- include "document-tokenizer.full.labels" . | nindent 4 }}
data: {{ include "document-tokenizer.env.secret" . | nindent 2 }}