apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-tokenizer.fullname" . }}
  labels:
    {{- include "document-tokenizer.full.labels" . | nindent 4 }}
spec:
  {{- if eq (lower .Values.service.type) "headless" }}
  type: ClusterIP
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "document-tokenizer.common.labels" . | nindent 4 }}
